// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_services.proto

package com.nghia.grpc.services.userService;

public final class UserServices {
  private UserServices() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023user_services.proto\032\023user_entities.pro" +
      "to2\217\001\n\013UserService\0229\n\014findUserById\022\024.Fin" +
      "dUserByIdRequest\032\021.FindUserResponse\"\000\022E\n" +
      "\022findUserByUsername\022\032.FindUserByUsername" +
      "Request\032\021.FindUserResponse\"\000B\'\n#com.nghi" +
      "a.grpc.services.userServiceP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.nghia.grpc.entities.user.UserEntities.getDescriptor(),
        });
    com.nghia.grpc.entities.user.UserEntities.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
