// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_entities.proto

package com.nghia.grpc.entities.user;

public interface FindUserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FindUserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.BaseResponse baseResponse = 1;</code>
   * @return Whether the baseResponse field is set.
   */
  boolean hasBaseResponse();
  /**
   * <code>.BaseResponse baseResponse = 1;</code>
   * @return The baseResponse.
   */
  com.nghia.grpc.entities.user.BaseResponse getBaseResponse();
  /**
   * <code>.BaseResponse baseResponse = 1;</code>
   */
  com.nghia.grpc.entities.user.BaseResponseOrBuilder getBaseResponseOrBuilder();

  /**
   * <code>int32 id = 2;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string username = 3;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 3;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string email = 4;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 4;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>bool isEnable = 5;</code>
   * @return The isEnable.
   */
  boolean getIsEnable();

  /**
   * <code>bool isLocked = 6;</code>
   * @return The isLocked.
   */
  boolean getIsLocked();

  /**
   * <code>.Role role = 7;</code>
   * @return The enum numeric value on the wire for role.
   */
  int getRoleValue();
  /**
   * <code>.Role role = 7;</code>
   * @return The role.
   */
  com.nghia.grpc.entities.user.Role getRole();
}
