// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_entities.proto

package com.nghia.grpc.entities.user;

public final class UserEntities {
  private UserEntities() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BaseResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BaseResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FindUserByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FindUserByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FindUserByUsernameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FindUserByUsernameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FindUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FindUserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023user_entities.proto\"=\n\014BaseResponse\022\014\n" +
      "\004code\030\001 \001(\t\022\016\n\006status\030\002 \001(\t\022\017\n\007message\030\003" +
      " \001(\t\"\203\001\n\010UserInfo\022\n\n\002id\030\001 \001(\005\022\020\n\010usernam" +
      "e\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\022\020\n\010isEnable\030\004 \001(\010" +
      "\022\020\n\010isLocked\030\005 \001(\010\022\021\n\tcreatedAt\030\006 \001(\t\022\023\n" +
      "\004role\030\007 \001(\0162\005.Role\"!\n\023FindUserByIdReques" +
      "t\022\n\n\002id\030\001 \001(\005\"-\n\031FindUserByUsernameReque" +
      "st\022\020\n\010username\030\001 \001(\t\"\235\001\n\020FindUserRespons" +
      "e\022#\n\014baseResponse\030\001 \001(\0132\r.BaseResponse\022\n" +
      "\n\002id\030\002 \001(\005\022\020\n\010username\030\003 \001(\t\022\r\n\005email\030\004 " +
      "\001(\t\022\020\n\010isEnable\030\005 \001(\010\022\020\n\010isLocked\030\006 \001(\010\022" +
      "\023\n\004role\030\007 \001(\0162\005.Role*&\n\004Role\022\010\n\004USER\020\000\022\t" +
      "\n\005ADMIN\020\001\022\t\n\005STAFF\020\002B \n\034com.nghia.grpc.e" +
      "ntities.userP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_BaseResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BaseResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BaseResponse_descriptor,
        new java.lang.String[] { "Code", "Status", "Message", });
    internal_static_UserInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserInfo_descriptor,
        new java.lang.String[] { "Id", "Username", "Email", "IsEnable", "IsLocked", "CreatedAt", "Role", });
    internal_static_FindUserByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_FindUserByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FindUserByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_FindUserByUsernameRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_FindUserByUsernameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FindUserByUsernameRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_FindUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_FindUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FindUserResponse_descriptor,
        new java.lang.String[] { "BaseResponse", "Id", "Username", "Email", "IsEnable", "IsLocked", "Role", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
