server:
  port: ${SERVER_PORT}

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/phonecardmarket
    username: root
    password: nghia
    driver-class-name: com.mysql.cj.jdbc.Driver

  config:
    import: classpath:/config/local.properties

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    timeout: ${REDIS_TIMEOUT}

grpc:
  server:
    port: ${GRPC_PORT}
    user-service:
      host: ${USER_SERVICE_GRPC_HOST}
      port: ${USER_SERVICE_GRPC_PORT}
      timeout: ${GRPC_TIMEOUT}