// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_entities.proto

package com.nghia.grpc.entities.user;

public interface UserInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string username = 2;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 2;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>bool isEnable = 4;</code>
   * @return The isEnable.
   */
  boolean getIsEnable();

  /**
   * <code>bool isLocked = 5;</code>
   * @return The isLocked.
   */
  boolean getIsLocked();

  /**
   * <code>string createdAt = 6;</code>
   * @return The createdAt.
   */
  java.lang.String getCreatedAt();
  /**
   * <code>string createdAt = 6;</code>
   * @return The bytes for createdAt.
   */
  com.google.protobuf.ByteString
      getCreatedAtBytes();

  /**
   * <code>.Role role = 7;</code>
   * @return The enum numeric value on the wire for role.
   */
  int getRoleValue();
  /**
   * <code>.Role role = 7;</code>
   * @return The role.
   */
  com.nghia.grpc.entities.user.Role getRole();
}
