server:
  port: 8050

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: root
    password: nghia
    url: jdbc:mysql://localhost:3306/phonecardmarket?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
